apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-openldap.fullname" . }}
  labels:
    {{- include "test-openldap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "test-openldap.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "test-openldap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ldap
              containerPort: 10389
              protocol: TCP
            - name: ldaps
              containerPort: 10636
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - ldapwhoami
                - -H
                - ldap://localhost:10389
                - -x
            initialDelaySeconds: 5
            periodSeconds: 15
          # readinessProbe:
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
